# Generated by Django 4.0.4 on 2022-04-27 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('titlear', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(max_length=255)),
                ('descriptionar', models.TextField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploadsone/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploadstow/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='uploadsthree/')),
                ('slug', models.SlugField(max_length=255)),
                ('thumbnailOne', models.ImageField(blank=True, null=True, upload_to='uploadsone/')),
                ('thumbnailTow', models.ImageField(blank=True, null=True, upload_to='uploadstow/')),
                ('thumbnailThree', models.ImageField(blank=True, null=True, upload_to='uploadsthree/')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='CategoryAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='FreePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='SilverPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
            ],
        ),
    ]
