# Generated by Django 4.0.4 on 2022-05-02 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_ads_options_alter_categoryads_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='silverpart',
            name='amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='silverpart',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=5),
        ),
        migrations.AlterField(
            model_name='silverpart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silverparts', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='silverpart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silverparts', to=settings.AUTH_USER_MODEL),
        ),
    ]
